import React from 'react';

export enum BadgeLevel {
    Beginner = 'Iniciante',
    Intermediate = 'Intermediário',
    Advanced = 'Avançado',
    Master = 'Mestre',
    Secret = 'Secreto',
}

export enum GamificationEvent {
    CHAT_STARTED = 'CHAT_STARTED',
    ASSISTANT_SWITCHED = 'ASSISTANT_SWITCHED',
    FILE_UPLOADED = 'FILE_UPLOADED',
    CHAT_RENAMED = 'CHAT_RENAMED',
    LANGUAGE_CHANGED = 'LANGUAGE_CHANGED',
    CHAT_DELETED = 'CHAT_DELETED',
    THEME_CHANGED = 'THEME_CHANGED',
    HISTORY_VIEWED = 'HISTORY_VIEWED',
    NOTIFICATION_INTERACTED = 'NOTIFICATION_INTERACTED',
    MESSAGE_SENT = 'MESSAGE_SENT',
    META_BADGE_CHECK = 'META_BADGE_CHECK',
    USER_RETURNED = 'USER_RETURNED',
    EASTER_EGG_FOUND = 'EASTER_EGG_FOUND',
    CLIPBOARD_COPY = 'CLIPBOARD_COPY',
}

export interface Badge {
    id: string;
    name: string;
    description: string;
    level: BadgeLevel;
    secret: boolean;
    event: GamificationEvent;
    target: number;
    icon: string;
    colorClass: {
        bg: string;
        text: string;
        progress: string;
    };
    hidden?: boolean;
    dependentBadges?: string[];
}

const NON_SECRET_BADGES_FOR_MASTER_BADGE = [
    'beginner_first_chat', 'beginner_presentation', 'beginner_first_upload', 'beginner_customizer', 'beginner_explorer',
    'intermediate_frequent_chatter', 'intermediate_renamer', 'intermediate_organizer', 'intermediate_active_uploader', 'intermediate_theme_swapper', 'intermediate_polyglot', 'intermediate_loyal_reader',
    'advanced_chatter_50', 'advanced_multi_assistant', 'advanced_expert_translator', 'advanced_notification_active', 'advanced_journey_creator',
    'master_chatter_200', 'master_strategist', 'master_complete_explorer', 'master_legendary_user'
];

export const BADGES: Badge[] = [
    // --- Beginner ---
    {
        id: 'beginner_first_chat',
        name: 'Primeiro Chat',
        description: 'Inicie sua primeira conversa com um assistente.',
        level: BadgeLevel.Beginner,
        secret: false,
        event: GamificationEvent.CHAT_STARTED,
        target: 1,
        icon: '💬',
        colorClass: { bg: 'bg-sky-500/10', text: 'text-sky-500', progress: 'bg-sky-500' },
    },
    {
        id: 'beginner_presentation',
        name: 'Apresentação Feita',
        description: 'Interaja com 2 ou mais assistentes diferentes.',
        level: BadgeLevel.Beginner,
        secret: false,
        event: GamificationEvent.ASSISTANT_SWITCHED,
        target: 2,
        icon: '🤝',
        colorClass: { bg: 'bg-violet-500/10', text: 'text-violet-500', progress: 'bg-violet-500' },
    },
    {
        id: 'beginner_first_upload',
        name: 'Primeiro Upload',
        description: 'Envie sua primeira imagem ou arquivo.',
        level: BadgeLevel.Beginner,
        secret: false,
        event: GamificationEvent.FILE_UPLOADED,
        target: 1,
        icon: '📎',
        colorClass: { bg: 'bg-emerald-500/10', text: 'text-emerald-500', progress: 'bg-emerald-500' },
    },
    {
        id: 'beginner_customizer',
        name: 'Personalizador',
        description: 'Renomeie pela primeira vez um chat no histórico.',
        level: BadgeLevel.Beginner,
        secret: false,
        event: GamificationEvent.CHAT_RENAMED,
        target: 1,
        icon: '🎨',
        colorClass: { bg: 'bg-amber-500/10', text: 'text-amber-500', progress: 'bg-amber-500' },
    },
    {
        id: 'beginner_explorer',
        name: 'Explorador Novato',
        description: 'Teste o recurso de tradução em outra língua.',
        level: BadgeLevel.Beginner,
        secret: false,
        event: GamificationEvent.LANGUAGE_CHANGED,
        target: 2, // en is default, so needs one more
        icon: '🔍',
        colorClass: { bg: 'bg-teal-500/10', text: 'text-teal-500', progress: 'bg-teal-500' },
    },

    // --- Intermediate ---
    {
        id: 'intermediate_frequent_chatter',
        name: 'Conversador Frequente',
        description: 'Complete 10 chats.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.CHAT_STARTED,
        target: 10,
        icon: '🔄',
        colorClass: { bg: 'bg-blue-500/10', text: 'text-blue-500', progress: 'bg-blue-500' },
    },
    {
        id: 'intermediate_renamer',
        name: 'Renomeador',
        description: 'Renomeie 5 chats diferentes.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.CHAT_RENAMED,
        target: 5,
        icon: '✏️',
        colorClass: { bg: 'bg-orange-500/10', text: 'text-orange-500', progress: 'bg-orange-500' },
    },
    {
        id: 'intermediate_organizer',
        name: 'Organizador',
        description: 'Exclua chats antigos do histórico.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.CHAT_DELETED,
        target: 1,
        icon: '📂',
        colorClass: { bg: 'bg-slate-500/10', text: 'text-slate-500', progress: 'bg-slate-500' },
    },
    {
        id: 'intermediate_active_uploader',
        name: 'Uploader Ativo',
        description: 'Envie 5 arquivos/imagens.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.FILE_UPLOADED,
        target: 5,
        icon: '📤',
        colorClass: { bg: 'bg-green-500/10', text: 'text-green-500', progress: 'bg-green-500' },
    },
    {
        id: 'intermediate_theme_swapper',
        name: 'Tema Alternado',
        description: 'Alterne entre Light e Dark Theme pela primeira vez.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.THEME_CHANGED,
        target: 1,
        icon: '🌗',
        colorClass: { bg: 'bg-indigo-500/10', text: 'text-indigo-500', progress: 'bg-indigo-500' },
    },
    {
        id: 'intermediate_polyglot',
        name: 'Poliglota',
        description: 'Use o site em 3 línguas diferentes.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.LANGUAGE_CHANGED,
        target: 3,
        icon: '🌍',
        colorClass: { bg: 'bg-rose-500/10', text: 'text-rose-500', progress: 'bg-rose-500' },
    },
    {
        id: 'intermediate_loyal_reader',
        name: 'Leitor Fiel',
        description: 'Revisite uma conversa salva no histórico.',
        level: BadgeLevel.Intermediate,
        secret: false,
        event: GamificationEvent.HISTORY_VIEWED,
        target: 1,
        icon: '📖',
        colorClass: { bg: 'bg-stone-500/10', text: 'text-stone-500', progress: 'bg-stone-500' },
    },

    // --- Advanced ---
    {
        id: 'advanced_chatter_50',
        name: 'Conversador 50+',
        description: 'Atinja a marca de 50 chats iniciados.',
        level: BadgeLevel.Advanced,
        secret: false,
        event: GamificationEvent.CHAT_STARTED,
        target: 50,
        icon: '🗨️',
        colorClass: { bg: 'bg-fuchsia-500/10', text: 'text-fuchsia-500', progress: 'bg-fuchsia-500' },
    },
    {
        id: 'advanced_multi_assistant',
        name: 'Multiassistente',
        description: 'Converse com todos os assistentes pelo menos uma vez.',
        level: BadgeLevel.Advanced,
        secret: false,
        event: GamificationEvent.ASSISTANT_SWITCHED,
        target: 6, // There are 6 assistants now
        icon: '🧑‍🤝‍🧑',
        colorClass: { bg: 'bg-purple-500/10', text: 'text-purple-500', progress: 'bg-purple-500' },
    },
    {
        id: 'advanced_expert_translator',
        name: 'Tradutor Experiente',
        description: 'Use todas as 5 línguas disponíveis.',
        level: BadgeLevel.Advanced,
        secret: false,
        event: GamificationEvent.LANGUAGE_CHANGED,
        target: 5,
        icon: '🔤',
        colorClass: { bg: 'bg-red-500/10', text: 'text-red-500', progress: 'bg-red-500' },
    },
    {
        id: 'advanced_notification_active',
        name: 'Notificação Ativa',
        description: 'Interaja pela primeira vez com uma notificação.',
        level: BadgeLevel.Advanced,
        secret: false,
        event: GamificationEvent.NOTIFICATION_INTERACTED,
        target: 1,
        icon: '🔔',
        colorClass: { bg: 'bg-yellow-500/10', text: 'text-yellow-500', progress: 'bg-yellow-500' },
    },
    {
        id: 'advanced_journey_creator',
        name: 'Criador de Jornada',
        description: 'Mantenha uma conversa ativa com mais de 30 mensagens.',
        level: BadgeLevel.Advanced,
        secret: false,
        event: GamificationEvent.MESSAGE_SENT,
        target: 30,
        icon: '🛤️',
        colorClass: { bg: 'bg-cyan-500/10', text: 'text-cyan-500', progress: 'bg-cyan-500' },
    },

    // --- Master ---
    {
        id: 'master_chatter_200',
        name: 'Conversador 200+',
        description: 'Ultrapasse a incrível marca de 200 chats.',
        level: BadgeLevel.Master,
        secret: false,
        event: GamificationEvent.CHAT_STARTED,
        target: 200,
        icon: '🏆',
        colorClass: { bg: 'bg-pink-500/10', text: 'text-pink-500', progress: 'bg-pink-500' },
    },
    {
        id: 'master_strategist',
        name: 'Estrategista',
        description: 'Organize seu espaço com mais de 20 chats renomeados.',
        level: BadgeLevel.Master,
        secret: false,
        event: GamificationEvent.CHAT_RENAMED,
        target: 20,
        icon: '🎯',
        colorClass: { bg: 'bg-lime-500/10', text: 'text-lime-500', progress: 'bg-lime-500' },
    },
    {
        id: 'master_complete_explorer',
        name: 'Explorador Completo',
        description: 'Teste todos os principais recursos pelo menos uma vez.',
        level: BadgeLevel.Master,
        secret: false,
        event: GamificationEvent.META_BADGE_CHECK,
        target: 8,
        icon: '🌌',
        colorClass: { bg: 'bg-cyan-500/10', text: 'text-cyan-500', progress: 'bg-cyan-500' },
        dependentBadges: [
            'beginner_first_upload', 'beginner_customizer', 'beginner_explorer',
            'intermediate_organizer', 'intermediate_theme_swapper', 'intermediate_loyal_reader',
            'advanced_notification_active', 'beginner_presentation'
        ]
    },
    {
        id: 'master_legendary_user',
        name: 'Usuário Lendário',
        description: 'Inicie 20 conversas com cada um dos 5 assistentes.',
        level: BadgeLevel.Master,
        secret: false,
        event: GamificationEvent.META_BADGE_CHECK,
        target: 6,
        icon: '🔥',
        colorClass: { bg: 'bg-red-500/10', text: 'text-red-500', progress: 'bg-red-500' },
        dependentBadges: [
            'hidden_legendary_zora', 'hidden_legendary_wizi', 'hidden_legendary_luma',
            'hidden_legendary_loki', 'hidden_legendary_iris', 'hidden_legendary_vyne'
        ]
    },
    {
        id: 'master_badge_master',
        name: 'Mestre das Badges',
        description: 'Conquiste todos os outros badges não secretos.',
        level: BadgeLevel.Master,
        secret: false,
        event: GamificationEvent.META_BADGE_CHECK,
        target: NON_SECRET_BADGES_FOR_MASTER_BADGE.length,
        icon: '🥇',
        colorClass: { bg: 'bg-yellow-500/10', text: 'text-yellow-500', progress: 'bg-yellow-500' },
        dependentBadges: NON_SECRET_BADGES_FOR_MASTER_BADGE,
    },


    // --- Secret ---
    {
        id: 'secret_night_owl',
        name: 'Corujão',
        description: 'Iniciou uma conversa entre 00h e 05h.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.CHAT_STARTED,
        target: 1,
        icon: '🌙',
        colorClass: { bg: 'bg-indigo-600/10', text: 'text-indigo-500', progress: 'bg-indigo-600' },
    },
     {
        id: 'secret_early_bird',
        name: 'Madrugador',
        description: 'Iniciou uma conversa antes das 06h.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.CHAT_STARTED,
        target: 1,
        icon: '☀️',
        colorClass: { bg: 'bg-amber-500/10', text: 'text-amber-500', progress: 'bg-amber-500' },
    },
    {
        id: 'secret_addict',
        name: 'Viciado',
        description: 'Iniciou 5 conversas diferentes no mesmo dia.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.CHAT_STARTED,
        target: 5,
        icon: '🔄',
        colorClass: { bg: 'bg-red-600/10', text: 'text-red-500', progress: 'bg-red-600' },
    },
    {
        id: 'secret_marathon_runner',
        name: 'Maratonista',
        description: 'Enviou 100 mensagens em uma única sessão de chat.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.MESSAGE_SENT,
        target: 100,
        icon: '🏃',
        colorClass: { bg: 'bg-lime-500/10', text: 'text-lime-500', progress: 'bg-lime-500' },
    },
    {
        id: 'secret_silent_one',
        name: 'Silencioso',
        description: 'Retornou ao site após 30 dias de inatividade.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.USER_RETURNED,
        target: 1,
        icon: '🤫',
        colorClass: { bg: 'bg-slate-500/10', text: 'text-slate-500', progress: 'bg-slate-500' },
    },
    {
        id: 'secret_file_shooter',
        name: 'Atirador de Arquivos',
        description: 'Enviou 10 arquivos em uma única sessão.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.FILE_UPLOADED,
        target: 10,
        icon: '📸',
        colorClass: { bg: 'bg-teal-500/10', text: 'text-teal-500', progress: 'bg-teal-500' },
    },
    {
        id: 'secret_easter_egg_discoverer',
        name: 'Descobridor de Easter Egg',
        description: 'Encontrou uma função oculta ou comando secreto.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.EASTER_EGG_FOUND,
        target: 1,
        icon: '🥚',
        colorClass: { bg: 'bg-yellow-400/10', text: 'text-yellow-400', progress: 'bg-yellow-400' },
    },
    {
        id: 'secret_crossover',
        name: 'Crossover',
        description: 'Copiou uma resposta de um assistente e continuou em outro.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.MESSAGE_SENT, // Logic is more complex
        target: 1,
        icon: '🔀',
        colorClass: { bg: 'bg-fuchsia-500/10', text: 'text-fuchsia-500', progress: 'bg-fuchsia-500' },
    },
    {
        id: 'secret_record_holder',
        name: 'Recordista',
        description: 'Atingiu 500 mensagens em um único histórico de chat.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.MESSAGE_SENT,
        target: 500,
        icon: '⏱️',
        colorClass: { bg: 'bg-sky-500/10', text: 'text-sky-500', progress: 'bg-sky-500' },
    },
    {
        id: 'secret_chameleon',
        name: 'Camaleão',
        description: 'Alterou o tema do site 10 vezes em um único dia.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.THEME_CHANGED,
        target: 10,
        icon: '🎭',
        colorClass: { bg: 'bg-purple-500/10', text: 'text-purple-500', progress: 'bg-purple-500' },
    },
    {
        id: 'secret_ninja_translator',
        name: 'Tradutor Ninja',
        description: 'Alternou entre as 5 línguas no mesmo chat.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.LANGUAGE_CHANGED,
        target: 5,
        icon: '🥷',
        colorClass: { bg: 'bg-gray-800/10', text: 'text-gray-800', progress: 'bg-gray-800' },
    },
    {
        id: 'secret_hidden_collector',
        name: 'Colecionador Oculto',
        description: 'Desbloqueou 10 badges em menos de 24 horas.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.META_BADGE_CHECK,
        target: 10,
        icon: '🗝️',
        colorClass: { bg: 'bg-amber-600/10', text: 'text-amber-600', progress: 'bg-amber-600' },
    },
    {
        id: 'secret_infinity_chat',
        name: 'Infinity Chat',
        description: 'Manteve uma conversa por 7 dias seguidos no mesmo histórico.',
        level: BadgeLevel.Secret,
        secret: true,
        event: GamificationEvent.MESSAGE_SENT,
        target: 7,
        icon: '♾️',
        colorClass: { bg: 'bg-violet-600/10', text: 'text-violet-600', progress: 'bg-violet-600' },
    },


    // --- Hidden Tracking Badges ---
    ...(['zora', 'wizi', 'luma', 'loki', 'iris', 'vyne'].map(assistantId => ({
        id: `hidden_legendary_${assistantId}`,
        name: `Legendary User (${assistantId.toUpperCase()})`,
        description: `Start 20 chats with ${assistantId.toUpperCase()}.`,
        level: BadgeLevel.Master,
        secret: false,
        hidden: true,
        event: GamificationEvent.CHAT_STARTED,
        target: 20,
        icon: '🔥',
        colorClass: { bg: 'bg-gray-500/10', text: 'text-gray-500', progress: 'bg-gray-500' },
    } as Badge))),
];